# Generated by Django 6.0 on 2026-03-05 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('hotel_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('nick_name', models.CharField(max_length=200)),
                ('about', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=20)),
                ('alternative_mobile', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=50, null=True, unique=True)),
                ('alternative_email', models.EmailField(max_length=50, null=True, unique=True)),
                ('established', models.DateField(null=True)),
                ('booking_status', models.CharField(choices=[('open', 'Open'), ('close', 'Close')], default='open', max_length=10, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('inactive', 'Inactive')], default='pending', max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'hotels',
            },
        ),
    ]
