# Generated by Django 6.0 on 2026-03-05 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='nick_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
