# Generated by Django 6.0 on 2026-03-07 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0002_alter_hotel_nick_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='established',
            field=models.DateField(blank=True, null=True),
        ),
    ]
