# Generated by Django 6.0 on 2026-03-01 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_admin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminuser',
            name='mobile',
            field=models.BigIntegerField(default=0),
        ),
    ]
