# Generated by Django 6.0 on 2026-03-01 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_admin', '0002_alter_adminuser_mobile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adminuser',
            options={},
        ),
        migrations.AlterModelTable(
            name='adminuser',
            table='auth_user',
        ),
    ]
