# Generated by Django 6.0 on 2026-03-01 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_admin', '0003_alter_adminuser_options_alter_adminuser_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminuser',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='adminuser',
            name='city',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='adminuser',
            name='district',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='adminuser',
            name='dob',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='adminuser',
            name='email',
            field=models.EmailField(max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='adminuser',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], default='male', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='adminuser',
            name='pincode',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='adminuser',
            name='profile_picture',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='adminuser',
            name='state',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='adminuser',
            name='status',
            field=models.CharField(default='pending', max_length=10, null=True),
        ),
    ]
