# Generated by Django 6.0 on 2026-03-07 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_room_hotel'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='max_capacity',
            field=models.IntegerField(default=1),
        ),
    ]
