# Generated by Django 6.0 on 2026-03-07 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_room_max_capacity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_number',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
